### ISSUE TITLE
Contao Manager ready

### ISSUE THREAD

**Issue by chriza** [terminal42/contao-calendar-categories#1]
Hallo,

leider wird die Extension marebe1602/mae_event_categories nicht weiterentwickelt.

Codefog hat mich auf diese Extension als Ersatz aufmerksam gemacht.

Wäre es möglich, diese Extension Contao Manager ready zu machen?

Viele Grüße
Christoph Zander

**Comment by aschempp** [comment]
ist mittlerweile erledigt
